
title = "I'm Jorge Ampuero"
author = "Jorge Ampuero"
copyright = "2023"
description = "Personal site just for fun"
profilePicture = "images/yo.jpeg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/yo.jpeg"]
doNotLoadAnimations = false
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
contactFormAction = "https://public.herotofu.com/v1/44b44200-a75b-11ed-a31e-753411848f80"



reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jampueroc/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jampueroc"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/_z4n63tsu_/"